server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: internship-management
  profiles:
    active: ${SPRING_PROFILE:dev}

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:aptiv_internship}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/aptiv}

  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.office365.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Flyway Migration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging
logging:
  level:
    com.aptiv.internship: DEBUG
    org.springframework.security: DEBUG

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Custom Properties
aptiv:
  internship:
    file-storage-path: ${FILE_STORAGE_PATH:/tmp/internship-files}
    notification:
      days-before-end: 30,7,1
      max-consecutive-absences: 5
    hr-email: ${HR_EMAIL:hr@aptiv.com}